version: "3.9"
services:
  postgres:
    image: postgres:14.11-alpine3.18
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=neko
      - POSTGRES_DB=uwupedia
    volumes:
      - uwupedia-data-slaves:/var/lib/postgresql/data

volumes:
  uwupedia-data-master:
  uwupedia-data-slaves: